[secrets] # These should be overwritten in the secrets.ini file
wifi_ssid = "WiFiNameGoesHere"
wifi_pass = "SuperSecretPassword"

[platformio]
extra_configs = secrets.ini

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
lib_deps = 
    paulstoffregen/OneWire @ ^2.3.7
    milesburton/DallasTemperature @ ^3.9.1
    olikraus/U8g2 @ ^2.35.19
    arduino-libraries/NTPClient @ ^3.2.1
    bblanchon/ArduinoJson @ ^7.0.0

board_build.filesystem = littlefs
board_build.littlefs_label = static
board_build.partitions = partitions.csv

build_flags = 
    -D WIFI_SSID='${secrets.wifi_ssid}'
    -D WIFI_PASS='${secrets.wifi_pass}'
    # Required for C3 internal USB Serial
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1