[secrets] # These should be overwritten in the secrets.ini file
wifi_ssid = "WiFiNameGoesHere"
wifi_pass = "SuperSecretPassword"

[platformio]
extra_configs = secrets.ini

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
lib_deps = 
    # Web & API
    https://github.com/mathieucarbou/ESPAsyncWebServer.git @ ^3.3.23
    https://github.com/mathieucarbou/AsyncTCP.git @ ^3.3.2
    bblanchon/ArduinoJson @ ^7.0.4

    # Display (SSD1315)
    olikraus/U8g2 @ ^2.35.19

    # Sensors (DS18B20)
    milesburton/DallasTemperature @ ^3.9.1
    paulstoffregen/OneWire @ ^2.3.8

    # Logic & Time
    br3ttb/PID @ ^1.2.1
    arduino-libraries/NTPClient @ ^3.2.1

board_build.filesystem = littlefs
board_build.littlefs_label = static
board_build.partitions = partitions.csv

build_flags = 
    -D WIFI_SSID='${secrets.wifi_ssid}'
    -D WIFI_PASS='${secrets.wifi_pass}'
    # Required for C3 internal USB Serial
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1